/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubio_avila_mario_tarea8.pkg1;

import Ejercicio1.Temperatura.TemperaturaGUI;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mario-PC
 * @version 190130.0_1
 */
public class MainGUI extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainGUI() {
        
        configurarVentana(); //Configuracion Propia
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Ejercicio1 = new javax.swing.JButton();
        Ejercicio2 = new javax.swing.JButton();
        Ejercicio3 = new javax.swing.JButton();
        lAboutProyect = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Ejercicio4 = new javax.swing.JButton();
        tEjercicio4 = new javax.swing.JLabel();
        mainToolBar = new javax.swing.JMenuBar();
        tbmArchivo = new javax.swing.JMenu();
        tbitemEjercicio1 = new javax.swing.JMenuItem();
        tbitemEjercicio2 = new javax.swing.JMenuItem();
        tbitemEjercicio3 = new javax.swing.JMenuItem();
        mEjercicio4 = new javax.swing.JMenuItem();
        tbitemSalir = new javax.swing.JMenuItem();
        tbmAyuda = new javax.swing.JMenu();
        tbmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(300, 250, 250, 250));
        setMaximumSize(new java.awt.Dimension(300, 250));
        setMinimumSize(new java.awt.Dimension(300, 250));
        setPreferredSize(new java.awt.Dimension(300, 250));

        Ejercicio1.setText("Ejercicio1");
        Ejercicio1.setToolTipText("Usuario Mario & Password 1234");
        Ejercicio1.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio1.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio1.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio1ActionPerformed(evt);
            }
        });

        Ejercicio2.setText("Ejercicio 2");
        Ejercicio2.setEnabled(false);
        Ejercicio2.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio2.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio2.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio2ActionPerformed(evt);
            }
        });

        Ejercicio3.setText("Ejercicio 3");
        Ejercicio3.setEnabled(false);
        Ejercicio3.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio3.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio3.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio3ActionPerformed(evt);
            }
        });

        lAboutProyect.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lAboutProyect.setForeground(new java.awt.Color(204, 204, 204));
        lAboutProyect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAboutProyect.setText("Rubio Avila Mario Tarea 8.1");
        lAboutProyect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("TEMPERATURA");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("LOTERIA");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("CATALOGO PELICULAS");

        Ejercicio4.setText("Ejercicio 4");
        Ejercicio4.setToolTipText("");
        Ejercicio4.setEnabled(false);
        Ejercicio4.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio4.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio4.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio4ActionPerformed(evt);
            }
        });

        tEjercicio4.setForeground(new java.awt.Color(204, 204, 204));
        tEjercicio4.setText("MATRICULA ALUMNADO");

        tbmArchivo.setText("Archivo");

        tbitemEjercicio1.setText("Ejercicio 1");
        tbitemEjercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemEjercicio1ActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemEjercicio1);

        tbitemEjercicio2.setText("Ejercicio 2");
        tbitemEjercicio2.setEnabled(false);
        tbitemEjercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemEjercicio2ActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemEjercicio2);

        tbitemEjercicio3.setText("Ejercicio 3");
        tbitemEjercicio3.setEnabled(false);
        tbitemEjercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemEjercicio3ActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemEjercicio3);

        mEjercicio4.setText("Ejercicio 4");
        mEjercicio4.setEnabled(false);
        mEjercicio4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mEjercicio4ActionPerformed(evt);
            }
        });
        tbmArchivo.add(mEjercicio4);

        tbitemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        tbitemSalir.setText("Salir");
        tbitemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemSalirActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemSalir);

        mainToolBar.add(tbmArchivo);

        tbmAyuda.setText("Ayuda");

        tbmAbout.setText("Acerca de...");
        tbmAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbmAboutMousePressed(evt);
            }
        });
        tbmAyuda.add(tbmAbout);

        mainToolBar.add(tbmAyuda);

        setJMenuBar(mainToolBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAboutProyect)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Ejercicio1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(Ejercicio2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ejercicio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ejercicio4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tEjercicio4)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tEjercicio4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(lAboutProyect)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ejercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio1ActionPerformed
         callEjercicio1();
    }//GEN-LAST:event_Ejercicio1ActionPerformed

    private void tbitemEjercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemEjercicio1ActionPerformed
         callEjercicio1();
    }//GEN-LAST:event_tbitemEjercicio1ActionPerformed

    private void tbitemEjercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemEjercicio2ActionPerformed
         callEjercicio2();
    }//GEN-LAST:event_tbitemEjercicio2ActionPerformed

    private void tbmAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmAboutMousePressed
        JOptionPane.showMessageDialog(this,"Rubio_Avila_Mario_Tarea 8.1\n","Acerca de...",1);//Mostamos acerca de en un cuadro de dialogo para saber el numero de tarea
    }//GEN-LAST:event_tbmAboutMousePressed

    private void tbitemEjercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemEjercicio3ActionPerformed
        callEjercicio3();
    }//GEN-LAST:event_tbitemEjercicio3ActionPerformed

    private void Ejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio2ActionPerformed
        callEjercicio2();
    }//GEN-LAST:event_Ejercicio2ActionPerformed

    private void Ejercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio3ActionPerformed
        callEjercicio3();
    }//GEN-LAST:event_Ejercicio3ActionPerformed

    private void Ejercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Ejercicio4ActionPerformed

    private void mEjercicio4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mEjercicio4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mEjercicio4ActionPerformed

    private void tbitemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_tbitemSalirActionPerformed
    
    /**
     * Vamos a darle un toque guay al ejercicio
     */
    private JLabel lblBackgroundImage = new JLabel();
    private JPanel panel1;
    String background = "/res/background/Background_Main.jpg";
    private void background(){
        //sets background image of panel
        //initializes panels and panel layout
        panel1 = new JPanel();
        lblBackgroundImage.setLayout(new FlowLayout());
        lblBackgroundImage.setIcon(new ImageIcon(background));
        panel1.add(lblBackgroundImage);
        validate();
    }//Fin de la decoracion
    
    //FUNCION PARA LA CONFIGURACION DE LA MAINFRAME
    private void configurarVentana() {
        this.setTitle("Rubio Avila Mario Tarea 8.1");           // Titulo a la ventana
        //La siguiente linea es para meter el fondo
        this.setContentPane(new JLabel(new javax.swing.ImageIcon(getClass().getResource("/res/background/Background_Main.jpg"))));
    }//Esto es para configurar la ventana 

    private void callEjercicio1(){
        TemperaturaGUI TGUI = new TemperaturaGUI(this,true);
        TGUI.setAlwaysOnTop(true);                              // Ventana siempre encima
        TGUI.setVisible(true); 
    }
    
    private void callEjercicio2(){

    }
    
    private void callEjercicio3(){

    }
    
    private void callEjercicio4(){

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejercicio1;
    private javax.swing.JButton Ejercicio2;
    private javax.swing.JButton Ejercicio3;
    private javax.swing.JButton Ejercicio4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lAboutProyect;
    private javax.swing.JMenuItem mEjercicio4;
    private javax.swing.JMenuBar mainToolBar;
    private javax.swing.JLabel tEjercicio4;
    private javax.swing.JMenuItem tbitemEjercicio1;
    private javax.swing.JMenuItem tbitemEjercicio2;
    private javax.swing.JMenuItem tbitemEjercicio3;
    private javax.swing.JMenuItem tbitemSalir;
    private javax.swing.JMenuItem tbmAbout;
    private javax.swing.JMenu tbmArchivo;
    private javax.swing.JMenu tbmAyuda;
    // End of variables declaration//GEN-END:variables
}
