/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rubio_avila_mario_tarea7;

import Ejercicio1.Login.LoginMain;
import Ejercicio2.Banco.BancoMain;
import Ejercicio3.Cifrado.CifradoMain;
import java.awt.FlowLayout;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Mario-PC
 * @version 190130.0_1
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        configurarVentana(); //Configuracion Propia
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        Ejercicio1 = new javax.swing.JButton();
        Ejercicio2 = new javax.swing.JButton();
        Ejercicio3 = new javax.swing.JButton();
        lAboutProyect = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mainToolBar = new javax.swing.JMenuBar();
        tbmArchivo = new javax.swing.JMenu();
        tbitemEjercicio1 = new javax.swing.JMenuItem();
        tbitemEjercicio2 = new javax.swing.JMenuItem();
        tbitemEjercicio3 = new javax.swing.JMenuItem();
        tbitemSalir = new javax.swing.JMenuItem();
        tbmAyuda = new javax.swing.JMenu();
        tbmAbout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(300, 250));
        setMinimumSize(new java.awt.Dimension(300, 250));
        setPreferredSize(new java.awt.Dimension(300, 250));

        Ejercicio1.setText("Ejercicio1");
        Ejercicio1.setToolTipText("Usuario Mario & Password 1234");
        Ejercicio1.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio1.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio1.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio1ActionPerformed(evt);
            }
        });

        Ejercicio2.setText("Ejercicio 2");
        Ejercicio2.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio2.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio2.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio2ActionPerformed(evt);
            }
        });

        Ejercicio3.setText("Ejercicio 3");
        Ejercicio3.setMaximumSize(new java.awt.Dimension(81, 30));
        Ejercicio3.setMinimumSize(new java.awt.Dimension(81, 30));
        Ejercicio3.setPreferredSize(new java.awt.Dimension(81, 30));
        Ejercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ejercicio3ActionPerformed(evt);
            }
        });

        lAboutProyect.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        lAboutProyect.setForeground(new java.awt.Color(204, 204, 204));
        lAboutProyect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lAboutProyect.setText("Rubio Avila Mario Tarea 7.1");
        lAboutProyect.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("LOGIN  Mario//1234");

        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("OPERACION BANCARIAS");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("CIFRADO CESAR");

        tbmArchivo.setText("Archivo");

        tbitemEjercicio1.setText("Ejercicio 1");
        tbitemEjercicio1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemEjercicio1ActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemEjercicio1);

        tbitemEjercicio2.setText("Ejercicio 2");
        tbitemEjercicio2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemEjercicio2ActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemEjercicio2);

        tbitemEjercicio3.setText("Ejercicio 3");
        tbitemEjercicio3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemEjercicio3ActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemEjercicio3);

        tbitemSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        tbitemSalir.setText("Salir");
        tbitemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbitemSalirActionPerformed(evt);
            }
        });
        tbmArchivo.add(tbitemSalir);

        mainToolBar.add(tbmArchivo);

        tbmAyuda.setText("Ayuda");

        tbmAbout.setText("Acerca de...");
        tbmAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tbmAboutMousePressed(evt);
            }
        });
        tbmAyuda.add(tbmAbout);

        mainToolBar.add(tbmAyuda);

        setJMenuBar(mainToolBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lAboutProyect)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Ejercicio1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Ejercicio2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(Ejercicio3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ejercicio3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(lAboutProyect)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Ejercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio1ActionPerformed
         callEjercicio1();
    }//GEN-LAST:event_Ejercicio1ActionPerformed

    private void tbitemEjercicio1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemEjercicio1ActionPerformed
         callEjercicio1();
    }//GEN-LAST:event_tbitemEjercicio1ActionPerformed

    private void tbitemEjercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemEjercicio2ActionPerformed
         callEjercicio2();
    }//GEN-LAST:event_tbitemEjercicio2ActionPerformed

    private void tbmAboutMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbmAboutMousePressed
        JOptionPane.showMessageDialog(this,"Rubio_Avila_Mario_Tarea 7.1\n","Acerca de...",1);//Mostamos acerca de en un cuadro de dialogo para saber el numero de tarea
    }//GEN-LAST:event_tbmAboutMousePressed

    private void tbitemEjercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemEjercicio3ActionPerformed
        callEjercicio3();
    }//GEN-LAST:event_tbitemEjercicio3ActionPerformed

    private void Ejercicio2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio2ActionPerformed
        callEjercicio2();
    }//GEN-LAST:event_Ejercicio2ActionPerformed

    private void Ejercicio3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ejercicio3ActionPerformed
        callEjercicio3();
    }//GEN-LAST:event_Ejercicio3ActionPerformed

    private void tbitemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbitemSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_tbitemSalirActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    
    
    /**
     * Vamos a darle un toque guay al ejercicio
     */
    private JLabel lblBackgroundImage = new JLabel();
    private JPanel panel1;
    String background = "/res/background/Background_Main.jpg";
    private void background(){
        //sets background image of panel
        //initializes panels and panel layout
        panel1 = new JPanel();
        lblBackgroundImage.setLayout(new FlowLayout());
        lblBackgroundImage.setIcon(new ImageIcon(background));
        panel1.add(lblBackgroundImage);
        validate();
    }//Fin de la decoracion
    
    //FUNCION PARA LA CONFIGURACION DE LA MAINFRAME
    private void configurarVentana() {
        this.setTitle("Rubio Avila Mario Tarea 7.1");           // Titulo a la ventana
        this.setSize(300, 200);                                 // Tamanio a la ventana (ancho y alto)
        this.setLocationRelativeTo(null);                       // Centrar Ventana
        this.setLayout(null);                                   // Sin Layaut predeterminado
        this.setResizable(false);                               // Ventano no redimensionable
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);    // Operacion de cierre de la ventana
        //La siguiente linea es para meter el fondo
        this.setContentPane(new JLabel(new javax.swing.ImageIcon(getClass().getResource("/res/background/Background_Main.jpg"))));
    }//Esto es para configurar la ventana 

    private void callEjercicio1(){
        LoginMain ejer1 = new LoginMain();
        ejer1.setAlwaysOnTop(true);                              // Ventana siempre encima
        ejer1.setVisible(true); 
    }
    
    private void callEjercicio2(){
        BancoMain ejer2 = new BancoMain();
        //ejer2.setAlwaysOnTop(true);                              // Ventana siempre encima
        ejer2.setVisible(true); 
    }
    
    private void callEjercicio3(){
        CifradoMain ejer3 = new CifradoMain();
        //ejer3.setAlwaysOnTop(true);                              // Ventana siempre encima
        ejer3.setVisible(true); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Ejercicio1;
    private javax.swing.JButton Ejercicio2;
    private javax.swing.JButton Ejercicio3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lAboutProyect;
    private javax.swing.JMenuBar mainToolBar;
    private javax.swing.JMenuItem tbitemEjercicio1;
    private javax.swing.JMenuItem tbitemEjercicio2;
    private javax.swing.JMenuItem tbitemEjercicio3;
    private javax.swing.JMenuItem tbitemSalir;
    private javax.swing.JMenuItem tbmAbout;
    private javax.swing.JMenu tbmArchivo;
    private javax.swing.JMenu tbmAyuda;
    // End of variables declaration//GEN-END:variables
}
