/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ejercicio2.Banco;

import javax.swing.JOptionPane;

/**
 *
 * @author Mario-PC
 */
public class BancoMain extends javax.swing.JDialog {
    
    boolean DEBUGMODE = false;// Se usa para el seguimiento del codigo habilita ciertos mensajes 
    cuenta Cliente;          //Almacenara al cliente en cuestion
    
    /**
     * Creates new form BancoMain
     */
    public BancoMain() {
        configurarVentana();
        initComponents();
        cargarCuenta();//Inicializa la clase cuenta lo separo por si en un futuro se necesita cogerla de un fichero o base de datos
        cargarDatos();// Da formato a los editText con los datos de la cuenta
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        etSaldoCuenta = new javax.swing.JTextField();
        etSaldoTarjeta = new javax.swing.JTextField();
        lSaldoCuenta = new javax.swing.JLabel();
        lSaldoTarjeta = new javax.swing.JLabel();
        bIngresoCuenta = new javax.swing.JButton();
        bIngresoTarjeta = new javax.swing.JButton();
        bSacarCuenta = new javax.swing.JButton();
        bSacarTarjeta = new javax.swing.JButton();
        bTransferirCuentaTarjeta = new javax.swing.JButton();
        lEstadoCuenta = new javax.swing.JLabel();
        lTitular = new javax.swing.JLabel();
        etTitular = new javax.swing.JTextField();
        bCerrarSesion = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miDesconectar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        mIngresarCuenta = new javax.swing.JMenuItem();
        mIngresarTarjeta = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        mRetirarCuenta = new javax.swing.JMenuItem();
        mRetirarTarjeta = new javax.swing.JMenuItem();
        mTransferir = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        mCambioNombreTitular = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 330));
        setResizable(false);

        etSaldoCuenta.setEditable(false);
        etSaldoCuenta.setFocusable(false);

        etSaldoTarjeta.setEditable(false);
        etSaldoTarjeta.setFocusable(false);

        lSaldoCuenta.setText("Saldo Cuenta");

        lSaldoTarjeta.setText("Saldo Tarjeta");

        bIngresoCuenta.setText("Ingresar en Cuenta");
        bIngresoCuenta.setToolTipText("Permite ingresar saldo de la cuenta");
        bIngresoCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresoCuentaActionPerformed(evt);
            }
        });

        bIngresoTarjeta.setText("Ingresar en Tarjeta");
        bIngresoTarjeta.setToolTipText("Permite ingresar saldo de la cuenta");
        bIngresoTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bIngresoTarjetaActionPerformed(evt);
            }
        });

        bSacarCuenta.setText("Sacar de la Cuenta");
        bSacarCuenta.setToolTipText("Permite retirar saldo de la cuenta");
        bSacarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSacarCuentaActionPerformed(evt);
            }
        });

        bSacarTarjeta.setText("Sacar de la Tarjeta");
        bSacarTarjeta.setToolTipText("Permite retirar saldo de la tarjeta");
        bSacarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSacarTarjetaActionPerformed(evt);
            }
        });

        bTransferirCuentaTarjeta.setText("Transferir de Cuenta a Tarjeta");
        bTransferirCuentaTarjeta.setToolTipText("Transfiere de cuenta a la tarjeta su saldo");
        bTransferirCuentaTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bTransferirCuentaTarjetaActionPerformed(evt);
            }
        });

        lEstadoCuenta.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lEstadoCuenta.setText("ESTADO DE LA CUENTA");

        lTitular.setText("Cliente : ");

        etTitular.setEditable(false);
        etTitular.setFocusable(false);

        bCerrarSesion.setText("Desconectar");
        bCerrarSesion.setToolTipText("Permite cerrar la session");
        bCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCerrarSesionActionPerformed(evt);
            }
        });

        jMenu1.setText("Archivo");

        miDesconectar.setText("Desconectar");
        miDesconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miDesconectarActionPerformed(evt);
            }
        });
        jMenu1.add(miDesconectar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Acciones");

        jMenu3.setText("Ingresar");

        mIngresarCuenta.setText("En Cuenta");
        mIngresarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIngresarCuentaActionPerformed(evt);
            }
        });
        jMenu3.add(mIngresarCuenta);

        mIngresarTarjeta.setText("En Tarjeta");
        mIngresarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mIngresarTarjetaActionPerformed(evt);
            }
        });
        jMenu3.add(mIngresarTarjeta);

        jMenu2.add(jMenu3);

        jMenu4.setText("Retirar");

        mRetirarCuenta.setText("En Cuenta");
        mRetirarCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRetirarCuentaActionPerformed(evt);
            }
        });
        jMenu4.add(mRetirarCuenta);

        mRetirarTarjeta.setText("En Tarjeta");
        mRetirarTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mRetirarTarjetaActionPerformed(evt);
            }
        });
        jMenu4.add(mRetirarTarjeta);

        jMenu2.add(jMenu4);

        mTransferir.setText("Tranferir");
        mTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mTransferirActionPerformed(evt);
            }
        });
        jMenu2.add(mTransferir);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Otros");

        mCambioNombreTitular.setText("Cambio nombre cliente");
        mCambioNombreTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mCambioNombreTitularActionPerformed(evt);
            }
        });
        jMenu5.add(mCambioNombreTitular);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bIngresoTarjeta)
                                .addGap(18, 18, 18)
                                .addComponent(bSacarTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bIngresoCuenta)
                                .addGap(18, 18, 18)
                                .addComponent(bSacarCuenta))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lTitular)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(etTitular)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bTransferirCuentaTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lSaldoCuenta)
                            .addComponent(lSaldoTarjeta))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(etSaldoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(etSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lEstadoCuenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lTitular)
                    .addComponent(etTitular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCerrarSesion))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bIngresoCuenta)
                            .addComponent(bSacarCuenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bIngresoTarjeta)
                            .addComponent(bSacarTarjeta)))
                    .addComponent(bTransferirCuentaTarjeta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(30, 30, 30)
                .addComponent(lEstadoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etSaldoCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSaldoCuenta))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(etSaldoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lSaldoTarjeta))
                .addGap(50, 50, 50))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bIngresoTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresoTarjetaActionPerformed
        IngresarTarjeta();
    }//GEN-LAST:event_bIngresoTarjetaActionPerformed

    private void bSacarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSacarTarjetaActionPerformed
        SacarTarjeta();
    }//GEN-LAST:event_bSacarTarjetaActionPerformed

    private void bTransferirCuentaTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bTransferirCuentaTarjetaActionPerformed
        Tranferir();
    }//GEN-LAST:event_bTransferirCuentaTarjetaActionPerformed

    private void bIngresoCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bIngresoCuentaActionPerformed
        IngresarCuenta();
    }//GEN-LAST:event_bIngresoCuentaActionPerformed

    private void bSacarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSacarCuentaActionPerformed
        SacarCuenta();
    }//GEN-LAST:event_bSacarCuentaActionPerformed

    private void bCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCerrarSesionActionPerformed
        this.dispose();
    }//GEN-LAST:event_bCerrarSesionActionPerformed

    private void miDesconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miDesconectarActionPerformed
        this.dispose();
    }//GEN-LAST:event_miDesconectarActionPerformed

    private void mIngresarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIngresarCuentaActionPerformed
        IngresarCuenta();
    }//GEN-LAST:event_mIngresarCuentaActionPerformed

    private void mIngresarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mIngresarTarjetaActionPerformed
        IngresarTarjeta();
    }//GEN-LAST:event_mIngresarTarjetaActionPerformed

    private void mRetirarCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRetirarCuentaActionPerformed
        SacarCuenta();
    }//GEN-LAST:event_mRetirarCuentaActionPerformed

    private void mRetirarTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mRetirarTarjetaActionPerformed
        SacarTarjeta();
    }//GEN-LAST:event_mRetirarTarjetaActionPerformed

    private void mTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mTransferirActionPerformed
        Tranferir();
    }//GEN-LAST:event_mTransferirActionPerformed

    private void mCambioNombreTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mCambioNombreTitularActionPerformed
        CambioNombre();
    }//GEN-LAST:event_mCambioNombreTitularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BancoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BancoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BancoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BancoMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BancoMain().setVisible(true);
            }
        });
    }
    
    //Paneles para operar con la cuenta.
    //Todos lo que sea doble se redondeara a dos cifras. Mas informacion sobre esto en carga datos.
    
    private void IngresarCuenta(){
        try{
            String ingreso = JOptionPane.showInputDialog(this, "Cuanto dinero deseas ingresar en la cuenta : ","Ingreso en cuenta",JOptionPane.QUESTION_MESSAGE);
            if(ingreso == null || (ingreso != null && ("".equals(ingreso)))) return;    //Si no deseo nada a la calle
            this.Cliente.ingresarSaldoCuenta((double)Math.round(Double.parseDouble(ingreso) * 100d) / 100d);
        }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Cantidad no valida, Compruebe que no inserto un caracter o que la coma es '.'.","Error de valor no esperado",JOptionPane.ERROR_MESSAGE);
        }
        cargarDatos();// Realizo una actualizacion de los estados de la cuenta
    }
    
    private void IngresarTarjeta(){
        try{
            String ingreso = JOptionPane.showInputDialog(this, "Cuanto dinero deseas ingresar en la tarjeta : ","Ingreso en la tarjeta",JOptionPane.QUESTION_MESSAGE);
            if(ingreso == null || (ingreso != null && ("".equals(ingreso)))) return;    //Si no deseo nada a la calle
            this.Cliente.ingresarSaldoTarjeta((double)Math.round(Double.parseDouble(ingreso) * 100d) / 100d);
        }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Cantidad no valida, Compruebe que no inserto un caracter o que la coma es '.'.","Error de valor no esperado",JOptionPane.ERROR_MESSAGE);
        }
        cargarDatos();// Realizo una actualizacion de los estados de la cuenta
    }

    private void SacarCuenta(){
        try{
            String ingreso = JOptionPane.showInputDialog(this, "Cuanto dinero deseas retirar de la cuenta : ","Retirada de saldo de la cuenta",JOptionPane.QUESTION_MESSAGE);
            if(ingreso == null || (ingreso != null && ("".equals(ingreso)))) return;    //Si no deseo nada a la calle
            this.Cliente.sacarSaldoCuenta((double)Math.round(Double.parseDouble(ingreso) * 100d) / 100d);
        }catch(ExceptionSaldoNegativo e){//Capturo una exception creada especialmente solo para esta ocasion
            JOptionPane.showMessageDialog(this,"El saldo de la cuenta es insuficiente","Saldo insuficiente",JOptionPane.ERROR_MESSAGE);
            if (DEBUGMODE)System.out.println ("La excepcion lanzada es : " + e);
        }catch(Exception e){
                JOptionPane.showMessageDialog(this,"Cantidad no valida, Compruebe que no inserto un caracter o que la coma es '.'.","Error de valor no esperado",JOptionPane.ERROR_MESSAGE);
        }
        cargarDatos();// Realizo una actualizacion de los estados de la cuenta
    }    
    
    private void SacarTarjeta(){
        try{
            String ingreso = JOptionPane.showInputDialog(this, "Cuanto dinero deseas retirar de la tarjeta : ","Retirada de saldo de la tarjeta",JOptionPane.QUESTION_MESSAGE);
            if(ingreso == null || (ingreso != null && ("".equals(ingreso)))) return;    //Si no deseo nada a la calle
            this.Cliente.sacarSaldoTarjeta((double)Math.round(Double.parseDouble(ingreso) * 100d) / 100d);
        }catch(ExceptionSaldoNegativo e){//Capturo una exception creada especialmente solo para esta ocasion
            JOptionPane.showMessageDialog(this,"El saldo de la tarjeta es insuficiente","Saldo insuficiente",JOptionPane.ERROR_MESSAGE);
            if (DEBUGMODE)System.out.println ("La excepcion lanzada es : " + e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Cantidad no valida, Compruebe que no inserto un caracter\n o que la coma es '.' .","Error de valor no esperado",JOptionPane.ERROR_MESSAGE);
            if (DEBUGMODE)System.out.println ("La excepcion lanzada es : " + e);
        }
        cargarDatos();// Realizo una actualizacion de los estados de la cuenta
    }
    
    private void Tranferir(){
        try{
            String ingreso = JOptionPane.showInputDialog(this, "Cuanto dinero deseas transferir de la cuenta a la tarjeta : ","Tranferencia de saldo a la tarjeta",JOptionPane.QUESTION_MESSAGE);
            if(ingreso == null || (ingreso != null && ("".equals(ingreso)))) return; //Si no deseo nada a la calle
            this.Cliente.transferirSaldoATarjeta((double)Math.round(Double.parseDouble(ingreso) * 100d) / 100d);
        }catch(ExceptionSaldoNegativo e){//Capturo una exception creada especialmente solo para esta ocasion
            JOptionPane.showMessageDialog(this,"El saldo de la cuenta es insuficiente","Saldo insuficiente",JOptionPane.ERROR_MESSAGE);
            if (DEBUGMODE)System.out.println ("La excepcion lanzada es : " + e);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Cantidad no valida, Compruebe que no inserto un caracter\n o que la coma es '.' .","Error de valor no esperado",JOptionPane.ERROR_MESSAGE);
            if (DEBUGMODE)System.out.println ("La excepcion lanzada es : " + e);
        }
        cargarDatos();// Realizo una actualizacion de los estados de la cuenta
    }
    
    
    //Permite el cambio del nombre
    private void CambioNombre(){
        try{
            String ingreso = JOptionPane.showInputDialog(this, "Indique el nuevo nombre y apellidos de titular \n(ATENCION OPERACION NO HABITUAL) ","Cambio de nombre del titular",JOptionPane.QUESTION_MESSAGE);
            if(ingreso == null || (ingreso != null && ("".equals(ingreso)))) return; //Si no deseo nada a la calle
            else Cliente.setTitular(ingreso);
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Cantidad no valida, Compruebe que no inserto un caracter\n o que la coma es '.' .","Error de valor no esperado",JOptionPane.ERROR_MESSAGE);
            if (DEBUGMODE)System.out.println ("La excepcion lanzada es : " + e);
        }
        cargarDatos();// Realizo una actualizacion de los estados de la cuenta
    }
    
    
    //Iniciadores de procesos
    
    //FUNCION PARA LA CONFIGURACION DE LA JDialog
    private void configurarVentana() {
        this.setTitle("Ejercicio 2: Cuenta Bancaria");          // Titulo a la ventana
        //this.setLocationRelativeTo(this);                       // Centrar Ventana
        this.setLayout(null);                                   // Sin Layaut predeterminado
        this.setResizable(false);                               // Ventano no redimensionable
        this.setModal(true);                                    // La hacemos modal para que coja el foco
        //La siguiente linea es para meter el fondo
    }//Esto es para configurar la ventana 
    
    private void cargarCuenta(){
        this.Cliente = new cuenta("Mario Rubio Avila",1500.15,1000.85);
    }
    
    private void cargarDatos(){
        etTitular.setText(Cliente.getTitular());
        
        //Como los saldos son doubles y solo queremos dos decimales despues de la coma vamos a redondear
        //Tenemos dos metodos aparentes de redondeo
        //Usando la clase BigDecimal , usando el método setScale (En este tenemos que instanciar un objero bigdecimal)
        //      BigDecimal bDecimal = new BigDecimal(number);
        //      bDecimal = bDecimal.setScale(2, RoundingMode.HALF_UP);
        //Mediante Math.Round() -> (double)Math.round(number * 100d) / 100d) 
        
        etSaldoCuenta.setText(Double.toString((double)Math.round(Cliente.getSaldoCuenta() * 100d) / 100d));
        etSaldoTarjeta.setText(Double.toString((double)Math.round(Cliente.getSaldoTarjeta() * 100d) / 100d));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCerrarSesion;
    private javax.swing.JButton bIngresoCuenta;
    private javax.swing.JButton bIngresoTarjeta;
    private javax.swing.JButton bSacarCuenta;
    private javax.swing.JButton bSacarTarjeta;
    private javax.swing.JButton bTransferirCuentaTarjeta;
    private javax.swing.JTextField etSaldoCuenta;
    private javax.swing.JTextField etSaldoTarjeta;
    private javax.swing.JTextField etTitular;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lEstadoCuenta;
    private javax.swing.JLabel lSaldoCuenta;
    private javax.swing.JLabel lSaldoTarjeta;
    private javax.swing.JLabel lTitular;
    private javax.swing.JMenuItem mCambioNombreTitular;
    private javax.swing.JMenuItem mIngresarCuenta;
    private javax.swing.JMenuItem mIngresarTarjeta;
    private javax.swing.JMenuItem mRetirarCuenta;
    private javax.swing.JMenuItem mRetirarTarjeta;
    private javax.swing.JMenuItem mTransferir;
    private javax.swing.JMenuItem miDesconectar;
    // End of variables declaration//GEN-END:variables
}
